### ISSUE TITLE
eggNOG的输出可能不适用于parse_eggNOG.py这个脚本了

### ISSUE THREAD

**Issue by li153348734** [Hua-CM/HuaSmallTools#3]
eggNOG更新了它的输出文件格式，这个脚本可能不适合现在的格式了
(R) [lihr@localhost cultivar_Lee]$ python ../HuaSmallTools-master/parse/parse_eggNOG.py -i out.emapper.annotations -g go.tb -O gmx -o cultivar_Lee
Traceback (most recent call last):
  File "../HuaSmallTools-master/parse/parse_eggNOG.py", line 134, in <module>
    main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
  File "../HuaSmallTools-master/parse/parse_eggNOG.py", line 117, in main
    file4KO.to_csv(os.path.join(out_dir, "KOannotation.tsv"), sep="\t", index=False)
  File "/home/lihr/software/miniconda3/envs/R/lib/python3.8/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/home/lihr/software/miniconda3/envs/R/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 185, in save
    f, handles = get_handle(
  File "/home/lihr/software/miniconda3/envs/R/lib/python3.8/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'cultivar_Lee/KOannotation.tsv'

**Comment by Hua-CM** [comment]
请先创建输出文件夹。

**Comment by li153348734** [comment]
是的，需要创建文件夹来输出GO/KO两个tsv文件，上一次用是很久之前了，但是现在eggNOG把原来的query_seqs.fa.emapper.annotations替换成了out.emapper.annotations，这两个文件的格式是不一样的，脚本提取的结果不正确，
(R) [lihr@localhost cultivar_Lee]$ head *
==> GOannotation.tsv <==
gene	GO	level
GlymaLee.01G000400	E	
GlymaLee.01G000600	EH	
GlymaLee.01G000700	S	
GlymaLee.01G000800	S	
GlymaLee.01G000900	-	
GlymaLee.01G001000	O	
GlymaLee.01G001100	U	
GlymaLee.01G001200	S	
GlymaLee.01G001300	I	

==> KOannotation.tsv <==
gene	KO	pathway	description
(R) [lihr@localhost cultivar_Lee]$
您可以试一试，他现在的网站输出结果非常快

**Comment by Hua-CM** [comment]
方便的话把您的注释结果发我看一下。您可以注意到这个脚本我前不久刚commit过，解决的就是您说的问题。

**Comment by li153348734** [comment]
怎么发给您呢？要的是eggNOG注释的结果吗？还是脚本对它的结果处理后得到的两个文件？

**Comment by li153348734** [comment]
http://eggnog-mapper.embl.de/job_status?jobname=MM_ke_8gor_
